name: aggiorna dati affluenza

on:
#  push:
#  repository_dispatch:
#  schedule:
#    - cron:  '55 */1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmod +x scrape
    - name: aggiorna dati
      env:
        SUPER_SECRET: ${{ secrets.IFTTT }}
      run: |-
        export PATH=$PATH:~/bin
        chmod +x ./referendumAffluenza.sh
        ./referendumAffluenza.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Data e ora aggiornamento: ${timestamp}" || exit 0
        git push
